
public interface IKeywords {

	String columns_tweets = "tid,"
			+ "uid,"
			+ "co_ord,"
			+ "contributors,"
			+ "fav_count,"
			+ "hashtags,"
			+ "images,"
			+ "is_retweet,"
			+ "is_retweeted,"
			+ "language,"
			+ "place,"
			+ "possibly_sensitive,"
			+ "quoted_status_id,"
			+ "reply_2_scr_name,"
			+ "reply_2_status_id,"
			+ "reply_2_user_id,"
			+ "retweet_author_name,"
			+ "retweet_count,"
			+ "retweet_id,"
			+ "scopes,"
			+ "source,"
			+ "timestamp,"
			+ "truncated,"
			+ "tweet,"
			+ "urls,"
			+ "user_mentions,"
			+ "user_name,"
			+ "user_timestamp,"
			+ "witheld_in_countries";

	String insert_query_tweets = "INSERT INTO tweets ("
			+ columns_tweets
			+ ") "
			+ "VALUES "
			+ "("
			+ "?,?,?,?,  ?,?,?,?,  ?,?,?,?,  ?,?,?,?,  ?,?,?,?,"
			+ "?,?,?,?,  ?,?,?,?, ?"
			+ ");";
	
	String columns_users = "uid,"
			+ "created_at,"
			+ "default_profile,"
			+ "default_profile_image,"
			+ "description,"
			+ "favourites_count,"
			+ "followers_count,"
			+ "friends_count,"
			+ "geo_enabled,"
			+ "lang,"
			+ "listed_count,"
			+ "location,"
			+ "name,"
			+ "profile_background_color,"
			+ "profile_background_image_url,"
			+ "profile_banner_url,"
			+ "profile_image_url,"
			+ "protected,"
			+ "screen_name,"
			+ "time_zone,"
			+ "tweets_count,"
			+ "url,"
			+ "urls,"
			+ "utc_offset,"
			+ "withheld_in_countries ";
	
	String insert_query_users = "INSERT INTO users ("
			+ columns_users
			+ ") "
			+ " VALUES "
			+ "("
			+ "?,?,?,?,  ?,?,?,?,  ?,?,?,?,  ?,?,?,?,  ?,?,?,?,"
			+ "?,?,?,?,  ?"
			+ ");";
	
	String[] words2 = {"abortion contraception",
			"abortion groups",
			"abortion advocates",
			"abortion laws",
			"abortion saving",
			"abortions decline",
			"birth control blacks",
			"birth control federation america",
			"birth control federation america bcfa",
			"birth control movement",
			"charges birth",
			"contraceptives abortion",
			"control abortion",
			"country abortion",
			"distraction birth",
			"forced abortion",
			"immoralities child",
			"infant mortality",
			"international abortion",
			"legal abortion",
			"maternal child health",
			"maternal death rate",
			"maternal health",
			"maternal mortality",
			"parenthood federation",
			"partial birth abortions",
			"planned parenthood eugenic",
			"planned parenthood international",
			"population control",
			"promote abortion",
			"refer hospital",
			"reproductive health",
			"reproductive rights",
			"silent abortion",
			"unborn children",
			"unintended pregnancies",
			"viewed birth control",
			"blacks endured",
			"prison system black men children",
			"black caucus",
			"amendment constitution",
			"black face",
			"black america",
			"breed race",
			"black commentators",
			"clinics black",
			"hates whites",
			"oppressive conditions",
			"oppressors matter",
			"oppressors taste",
			"speaks black",
			"superior race",
			"title=blackamericans enemies",
			"whites america",
			"obama birth certificate issue",
			"calls black",
			"community racist",
			"day black",
			"brlp black",
			"brutality amendment",
			"freedom justice",
			"slave trader",
			"black black crimes",
			"black churches open intelligent propaganda",
			"black minister",
			"black obama",
			"black people good slaves",
			"black sheep spirit descendants slaves america",
			"called negroes",
			"fox hates blacks black obama",
			"house negro",
			"implementation negro project",
			"muslim obama natural born citizen",
			"national negro",
			"negro black man arrived houston buzzard landed christian",
			"negro jew",
			"negro lost",
			"negro newspapers",
			"negro project",
			"obama demonstrates black black caucus dinner obama elected",
			"slave heartless",
			"black americans undeserving citizenship bitch moan talk",
			"obama pimped black people",
			"unemployment rate higher",
			"unified resistance",
			"trillion spent",
			"government aggressively",
			"government refused",
			"hard movement",
			"military crisis",
			"obama police",
			"political cesspool",
			"power elite",
			"rule obama",
			"state involved",
			"arrest obama",
			"corrupt politician",
			"hatred government",
			"leftist government",
			"paid leadership",
			"politically incorrect",
			"villainous minister",
			"terrorists government",
			"armed hands",
			"guns citizen",
			"bear arms",
			"filed gunowners",
			"gun corner",
			"crime gunowners",
			"high priority",
			"homeland group",
			"ice homeland security investigations hsi",
			"agency workforce",
			"immigration enforcement",
			"immigration laws",
			"immigration customs enforcement",
			"drug trafficking",
			"national security",
			"national center",
			"border control",
			"week ice",
			"homeland security",
			"ice homeland security investigations",
			"homeland security investigations",
			"human exploitation",
			"law enforcement",
			"ny ice",
			"area border",
			"immigration customs enforcement",
			"public safety",
			"immigration customs enforcement ice",
			"agents immigration",
			"governing border",
			"america immigration",
			"american people",
			"security investigations",
			"border protection",
			"black market",
			"targeted transnational",
			"bring job",
			"caribbean corridor",
			"chiefs police",
			"citizenship immigration",
			"immigration legislation",
			"asylum work",
			"investigation immigration",
			"nation immigration",
			"operations ero",
			"cocaine arrested",
			"operation warfighter",
			"operation community",
			"protect american",
			"recruit qualified",
			"rights violations",
			"rights violators",
			"safe haven",
			"safety security",
			"salvadoran man",
			"secured borders",
			"secured immigration",
			"protecting homeland",
			"office immigration",
			"officers immigration",
			"officers special",
			"bay area",
			"tunnel discovered",
			"border drug",
			"border enforcement",
			"combating illegal",
			"control enforcement",
			"counterfeit goods",
			"counterfeit merchandise",
			"country aggravated",
			"critical arizona",
			"cultural property",
			"cultural treasures",
			"customs laws",
			"customs trade",
			"detains individuals",
			"diego area",
			"diego tunnel",
			"drug tunnel",
			"efficient enforcement",
			"el chapo",
			"el paso",
			"empowered illegal",
			"enforcement agency",
			"enforcement authorities",
			"enforcement effort",
			"enforcement officers",
			"enforcement officials",
			"enforcement operation",
			"enforcement personnel",
			"enforcement skills",
			"existing immigration",
			"face justice",
			"fallen law",
			"falling prey",
			"federal coordinating",
			"federal law",
			"federal prison",
			"federal state",
			"filed immigration",
			"foreign government",
			"foreign nationals",
			"ice mission",
			"ice yorkers",
			"identification arrest",
			"illegal importation",
			"illegal movement",
			"illegally export",
			"illegally imported",
			"illegally smuggled",
			"illegals happening",
			"illegals preventable",
			"immigrants enforcement",
			"immigrants illegal",
			"immigration control",
			"immigration fraud",
			"immigration process",
			"immigration promote",
			"immigration services",
			"immigration status",
			"immigration system",
			"immigration systems",
			"immigration violators",
			"international criminal",
			"international law",
			"international smuggling",
			"international students",
			"interpol alerts",
			"items protect",
			"joint investigation",
			"laws borders",
			"laws enforced",
			"laws governing",
			"led immigration",
			"legal immigrants",
			"living illegally",
			"los angeles",
			"maintains borders",
			"police department",
			"marriage fraud",
			"mexican authorities",
			"mexican government",
			"mexican law",
			"mexican man",
			"mexican nationals",
			"mexico border",
			"mexico city",
			"money laundering",
			"only immigration",
			"organizations illegally",
			"project iguardian",
			"promote homeland",
			"protect borders",
			"security officials",
			"security support",
			"seized kilograms",
			"sell counterfeit",
			"serving country",
			"silk road",
			"smart immigration",
			"sophisticated cross",
			"sophisticated smuggling",
			"sophisticated transnational",
			"southern border",
			"southwest border",
			"special operations",
			"strike force",
			"tons marijuana",
			"trade immigration",
			"traffic local",
			"trafficking charges",
			"trafficking human",
			"trafficking learn",
			"trafficking money",
			"trafficking offenses",
			"trafficking organizations",
			"trafficking prevention",
			"trafficking read",
			"trafficking ring",
			"trafficking task",
			"trafficking victims",
			"transnational drug",
			"transportation industries",
			"trespassers land",
			"tunnel task",
			"yorkers immigration",
			"wildlife trafficking",
			"brown mexican",
			"turned mexican",
			"mexican national",
			"alien smuggling",
			"mexican illegal",
			"undocumented immigrants",
			"alien trespassers",
			"hispanic supremacist",
			"day slavery",
			"alien college",
			"illegals mexico",
			"illegal alien",
			"alien population",
			"mexico face",
			"alien trespassing",
			"aliens undocumented",
			"associates gangs",
			"mexico serenity",
			"harboring illegal",
			"supporters illegal",
			"suspected child",
			"suspected human",
			"suspicious activity",
			"alien qualms",
			"dangerous transnational",
			"transnational criminal",
			"child rape",
			"laundering drug",
			"criminal foreign",
			"terrorists criminals",
			"terrorist criminal",
			"charges extradition",
			"deported ice",
			"wanted human",
			"violent criminals",
			"aliens convicted",
			"predator councilman",
			"immigration criminal",
			"drug traffickers",
			"raped illegal",
			"terrorism task",
			"aliens removed",
			"raped mexican",
			"sexual predators",
			"child predators",
			"criminal alien",
			"criminal aliens",
			"deported mexican",
			"deported officers",
			"aliens criminal",
			"extradited mexico",
			"child exploitation",
			"child pornography",
			"combat criminal",
			"crimes center",
			"crimes ice",
			"criminal activity",
			"criminal gangs",
			"criminal network",
			"criminal records",
			"criminals pose",
			"enforcement removal operations",
			"exploited children",
			"foreign fugitives",
			"fugitive alien",
			"fugitive operations",
			"fugitive unknown",
			"fugitive wanted",
			"fugitives active",
			"fugitives list",
			"gang members",
			"gangs arrested",
			"human smugglers",
			"human smuggling",
			"human traffickers",
			"human trafficking",
			"marijuana arresting",
			"mexican fugitive"};
	
//	String[] words1 = {"hate groups",
//			"vision white",
//			"kke anti",
//			"racist zionist",
//			"racist interlopers",
//			"ahepa refuses",
//			"politicians racist",
//			"differences racial",
//			"beat white",
//			"white britain",
//			"south africans",
//			"police race",
//			"white bystanders",
//			"acknowledge race",
//			"immigration free",
//			"white detractors",
//			"kkk defiance",
//			"africa",
//			"rhodesia",
//			"zimbabwe",
//			"detroit",
//			"derbyshire",
//			"mexico",
//			"texas",
//			"ferguson",
//			"mississippi",
//			"luzerne county",
//			"south carolina",
//			"iowa state",
//			"di fatima",
//			"holy eucharist",
//			"fatima crusader",
//			"planned parenthood",
//			"church teaching",
//			"true catholic",
//			"universal church",
//			"religious liberty",
//			"church teaches",
//			"religious freedom",
//			"holy viaticum",
//			"final battle",
//			"pro life",
//			"doctrine faith",
//			"catholic theology",
//			"false religion",
//			"holy tabernacles",
//			"jesus eucharist",
//			"gay marriage",
//			"nuclear war",
//			"dogma faith",
//			"divine law",
//			"birth control",
//			"pro abortion",
//			"false gods",
//			"love eucharistic",
//			"dogma catholic",
//			"cardinal ottaviani",
//			"rite ordination",
//			"adoration eucharist",
//			"lumen gentium",
//			"false ecumenism",
//			"catholic",
//			"immaculate",
//			"eucharist",
//			"antipope",
//			"doctrine",
//			"heretic",
//			"apostolate",
//			"abortion",
//			"heresies",
//			"apostasy",
//			"apostolic",
//			"persecution",
//			"catechism",
//			"augustine",
//			"ecclesiastical law",
//			"church pagans",
//			"eucharistic species",
//			"anti catholic",
//			"family planning",
//			"reject christ",
//			"vatican",
//			"heretics",
//			"heretical",
//			"incardination",
//			"bernadette",
//			"vescovi",
//			"alacoque",
//			"monsignor",
//			"fatima",
//			"catholics",
//			"christians",
//			"protestant",
//			"protestants",
//			"catholic faith",
//			"traditional catholic",
//			"catholic religion",
//			"catholic doctrine",
//			"russian orthodox",
//			"hold catholic",
//			"jews heretics",
//			"eastern orthodox",
//			"orthodox",
//			"cattolici",
//			"catechism council",
//			"christian unity",
//			"Fatima Crusader",
//			"Fatima Rosary Crusade",
//			"Catholic Family",
//			"Most Holy Family Monastery",
//			"fatima center",
//			"persecutions church",
//			"alphonsus",
//			"assisi",
//			"father gruner",
//			"lady fatima",
//			"pope pius",
//			"gemma galgani",
//			"terzo segreto",
//			"nicholas gruner",
//			"della chiesa",
//			"thomas aquinas",
//			"peter dimond",
//			"christopher ferrara",
//			"joseph cupertino",
//			"epistle gospel",
//			"mary magdalen",
//			"della fede",
//			"philip neri",
//			"john chrysostom",
//			"heretics schismatics",
//			"paschal baylon",
//			"di pazzi",
//			"catherine siena",
//			"john vennari",
//			"joseph ratzinger",
//			"joseph cottolengo",
//			"francis xavier",
//			"della madonna",
//			"robert bellarmine",
//			"fatima lady",
//			"saint maximilian",
//			"alphonsus liguori",
//			"charles borromeo",
//			"congregation clergy",
//			"papa giovanni",
//			"trinity father",
//			"cardinal sodano",
//			"jacinta francisco",
//			"catherine genoa",
//			"michael dimond",
//			"bishop fatima",
//			"maximilian kolbe",
//			"peter julian",
//			"julian eymard",
//			"paul kramer",
//			"shrine rector",
//			"chris ferrara",
//			"cantate domino",
//			"benedict xvi",
//			"chantal diligent",
//			"antipope john",
//			"pio pietrelcina",
//			"true church",
//			"fatima shrine",
//			"triumph immaculate",
//			"pope bishops",
//			"chiesa cattolica",
//			"cardinal bertone",
//			"fatima apostolate",
//			"sacred scripture",
//			"religious order",
//			"children fatima",
//			"jesus disciples",
//			"holy catholic",
//			"teaching catholic",
//			"reparation outrages",
//			"defined dogma",
//			"outrages sacrileges",
//			"catholic priest",
//			"false traditionalists",
//			"magdalen pazzi",
//			"catholic churches",
//			"lucy fatima",
//			"holy church",
//			"true religion",
//			"church taught",
//			"traditional catholics",
//			"catholics saved",
//			"fatima warnings",
//			"fatima perspectives",
//			"catholic truth",
//			"archbishop capovilla",
//			"eastern schismatics",
//			"concilio vaticano",
//			"god condemns",
//			"persecution church",
//			"pope catholic",
//			"leiria fatima",
//			"prefect congregation",
//			"fatima apparitions",
//			"salvation dogma",
//			"eucharist satisfaction",
//			"church exalts",
//			"eucharist gravely",
//			"fatima immaculate",
//			"fatima taught",
//			"eucharist true",
//			"consecration",
//			"divine",
//			"consecrated",
//			"crusader",
//			"apparitions",
//			"apparition",
//			"devotion saints",
//			"servants",
//			"police brutality",
//			"racist police",
//			"racist oppressors",
//			"black lives",
//			"slave trade",
//			"civil rights",
//			"slave masters",
//			"black violence",
//			"protect black",
//			"black unity",
//			"racist government",
//			"racist amerikkka",
//			"ruling elite",
//			"slave ships",
//			"civil war",
//			"black defense",
//			"black slave",
//			"black liberation",
//			"black slaves",
//			"slavery",
//			"liberation",
//			"shooting",
//			"conflict",
//			"blacklivesmatter",
//			"brutality",
//			"gang",
//			"ecclesiasticus",
//			"blackriders",
//			"romans",
//			"caucasian",
//			"black men",
//			"african americans",
//			"american indians",
//			"american blacks",
//			"black person",
//			"puerto ricans",
//			"white men",
//			"black riders",
//			"black rider",
//			"nation israel",
//			"israel united",
//			"iuic podcast",
//			"iuic",
//			"black riders liberation party",
//			"Israelite School of Universal and Practical Knowledge",
//			"Israel United In Christ",
//			"All Eyes On Egipt Bookstore Brooklyn NY",
//			"Nation of Islam",
//			"shawarma mayor",
//			"isupk",
//			"baltimore",
//			"south ossetia",
//			"north ossetia",
//			"putnam county",
//			"mosque maryam",
//			"dr malachi",
//			"louis farrakhan",
//			"george jackson",
//			"ezell ford",
//			"michael brown",
//			"martin luther",
//			"luther king",
//			"freddie gray",
//			"ishmael muhammad",
//			"sheriff howard",
//			"alex jones",
//			"mother tynnetta",
//			"david nowak",
//			"tbilisi georgia",
//			"berry moscow",
//			"heintz vladimir",
//			"chris torchia",
//			"pauline jelinek",
//			"wolverine shakur",
//			"grigory karasin",
//			"epistle paul",
//			"jesse jackson",
//			"sandra adams",
//			"jim crow",
//			"urim thummim",
//			"nabab yaanuwn",
//			"john hawkins",
//			"elijah muhammad",
//			"dr king",
//			"white supremacy",
//			"lives matter",
//			"black children",
//			"struggle black",
//			"slave master",
//			"justice equality",
//			"gang truces",
//			"patrol racist",
//			"tribe shabazz",
//			"black militant",
//			"retaliation racist",
//			"truces hoods",
//			"manipulated racist",
//			"police oppression",
//			"murder black",
//			"separatists declared",
//			"brutality murder",
//			"defending black",
//			"black leaders",
//			"israelites",
//			"slave",
//			"slaves",
//			"nypd",
//			"nuwaubians",
//			"movement",
//			"resistance",
//			"minded",
//			"dilution",
//			"anti-white",
//			"gruner",
//			"justice",
//			"sovereignty",
//			"anti-western",
//			"radical",
//			"racially",
//			"pig"
//};
	
	
	
//	String[] words = {"mass immigration",
//			"resistance movement",
//			"multicultural agenda",
//			"immigration dilution",
//			"anti white",
//			"racial issues",
//			"black diversity",
//			"black rule",
//			"africa project",
//			"white people",
//			"illegal aliens",
//			"race war",
//			"anti western",
//			"emancipate anti",
//			"boer war",
//			"gunowners rights",
//			"africa communist",
//			"racial differences",
//			"africa history",
//			"africa boer",
//			"defending borders",
//			"borders preserving",
//			"white discrimination",
//			"aliens immigration",
//			"amendment rights",
//			"socialist movement",
//			"movement racist",
//			"white ethnostate",
//			"rights freedom",
//			"anarchist gangs",
//			"illegal immigration",
//			"race riots",
//			"hispanic offenders",
//			"offenders african",
//			"race equality",
//			"existent threats",
//			"rejects equality",
//			"border security",
//			"mexican border",
//			"border war",
//			"border wall",
//			"multicultural",
//			"diversity",
//			"freedom",
//			"race",
//			"nationalist",
//			"leftist",
//			"violence",
//			"boer",
//			"marxism",
//			"racist",
//			"equality",
//			"discrimination",
//			"borders",
//			"nationalism",
//			"islam",
//			"apartheid",
//			"immigrants",
//			"zionism",
//			"capitalism",
//			"constitution",
//			"socialist",
//			"gangs",
//			"multiculturalism",
//			"holodomor",
//			"communsim",
//			"border",
//			"racism",
//			"marxist",
//			"minority",
//			"drugs",
//			"demilitarization",
//			"socialism",
//			"diaspora",
//			"ethnostate",
//			"holocaust",
//			"multiracialism",
//			"minorities",
//			"zionism quoted",
//			"civilized hate",
//			"whites extermination",
//			"racial hate",
//			"southern heritage",
//			"illegal immigrants",
//			"genocide white",
//			"muslim immigrants",
//			"mob attacks",
//			"biodiversity heritage",
//			"gun control",
//			"black community",
//			"racial hatred",
//			"white victims",
//			"whites forced",
//			"black race",
//			"racial slurs",
//			"attacks white",
//			"nationalism race",
//			"white privilege",
//			"white murders",
//			"gang rape",
//			"white farmers",
//			"african immigrants",
//			"holocaust denial",
//			"drug cartels",
//			"black robbers",
//			"sunni jihadists",
//			"anti gentilism",
//			"american jews",
//			"racial slur",
//			"white nationalist",
//			"european americans",
//			"white supremacist",
//			"white victim",
//			"white countries",
//			"anti immigration",
//			"christian civilization",
//			"anti gun",
//			"white conservatives",
//			"holocaust denier",
//			"fear jews",
//			"black mobs",
//			"illegal immigrant",
//			"white america",
//			"immigration reform",
//			"murdered white",
//			"radical black",
//			"white supremacists",
//			"asylum seekers",
//			"anti christ",
//			"diversity genocide",
//			"drug gangs",
//			"anti communist",
//			"white racism",
//			"racist white",
//			"immigration law",
//			"murdering white",
//			"sharia law",
//			"white forced",
//			"muslim immigration",
//			"radical islam",
//			"racial violence",
//			"white confederate",
//			"white majority",
//			"confederate flags",
//			"homosexual",
//			"homosexuals",
//			"establishment",
//			"confederate battle",
//			"confederate monument",
//			"confederate veterans",
//			"confederate monuments",
//			"confederate memorial",
//			"confederate states",
//			"confederate soldiers",
//			"confederate symbols",
//			"confederate soldier",
//			"confederate heritage",
//			"confederates",
//			"white",
//			"black",
//			"european",
//			"whites",
//			"african",
//			"jewish",
//			"jews",
//			"blacks",
//			"greeks",
//			"rhodesians",
//			"muslims",
//			"nazis",
//			"hispanic",
//			"africans",
//			"zionist",
//			"mexican",
//			"jew",
//			"hispanics",
//			"arab",
//			"european american",
//			"white man",
//			"black people",
//			"heritage european",
//			"black male",
//			"black majority",
//			"civilization white",
//			"european knights",
//			"europe jewish",
//			"black males",
//			"attacked white",
//			"white race",
//			"african american",
//			"black muslims",
//			"white women",
//			"zionist groups",
//			"anti greek",
//			"muslims black",
//			"white crime",
//			"black thugs",
//			"victims white",
//			"white students",
//			"nationalism black",
//			"white americans",
//			"black history",
//			"black power",
//			"white european",
//			"innocent white",
//			"white hispanic",
//			"white american",
//			"white folks",
//			"american whites",
//			"whites group",
//			"jewish homeland",
//			"white zionism",
//			"jews marxism",
//			"pro white",
//			"jewish groups",
//			"freedom party",
//			"left wing",
//			"nationalist party",
//			"black nationalism",
//			"political velcraft",
//			"people nationalist",
//			"ku klux",
//			"klux klan",
//			"klan ahepa",
//			"neo nazis",
//			"black panther",
//			"al qaeda",
//			"nazis kkk",
//			"whites amren",
//			"splc",
//			"nsm",
//			"afp",
//			"amren",
//			"sacp",
//			"naacp",
//			"darkmoon",
//			"ahepa",
//			"bollyn",
//			"velcraft",
//			"isis",
//			"adl",
//			"kke",
//			"kkk",
//			"nbpp",
//			"nazi",
//			"Loyal White Knights of the Ku Klux Klan",
//			"Racial Nationalist Party of America",
//			"Militant Knights Ku Klux Klan",
//			"Advanced White Society facebook",
//			"Ku Klos Knights of the Ku Klux Klan",
//			"Right Wing Resistance",
//			"Council of Conservative Citizens",
//			"Golden Dawn",
//			"Blood and Honour Social Club",
//			"National Socialist Movement, Syracuse, New York",
//			"National Socialist MovementNew York (statewide)",
//			"Aryan Strikeforce, New York",
//			"South Africa Project, NY",
//			"White Voice, TheNew York",
//			"American Freedom Party",
//			"bill johnson",
//			"steve smith",
//			"michael walsh",
//			"pamphlets aryan",
//			"karathanasis panagiotis",
//			"jared taylor",
//			"trayvon martin",
//			"donald trump",
//			"paul fromm",
//			"james kelso",
//			"sam dickson",
//			"al sharpton",
//			"matt heimbach",
//			"philippe rushton",
//			"trayvon",
//			"racial",
//			"hustlers",
//			"emancipate",
//			"conservative",
//			"aliens",
//			"renegade",
//			"americans",
//			"communists",
//			"muslim",
//			"tribune",
//			"thugs",
//			"conservatives",
//			"criminals",
//			"ethnic",
//			"miscegenation",
//			"racists",
//			"offenders",
//			"minded individuals",
//			"dilution european",
//			"rights identity",
//			"colonial rights",
//			"destroy colonial",
//			"local activist",
//			"american freedom",
//			"hate crimes",
//			"golden dawn",
//			"diversity strength",
//			"lack diversity",
//			"diversity anti",
//			"slogan diversity",
//			"disappointed white",
//			"white weak",
//			"white court",
//			"white courthouse",
//			"diversity county",
//			"posted anti",
//			"race hustlers",
//			"hate crime",
//			"white genocide",
//			"crimes racial",
//			"white hate",
//			"discrimination whites",
//			"social nationalists",
//			"majority rule",
//			"racially motivated",
//			"cultural marxism",
//			"marxism culture",
//			"war rhodesia",
//			"apartheid black",
//			"war apartheid",
//			"african crisis",
//			"boer farm",
//			"zion traitors",
//			"tribally zionism",
//			"european guardian",
//			"zionism traditional",
//			"culture equality",
//			"crime racial",
//			"promoting culture",
//			"greatest nationalist",
//			"national socialist"
//};
//	
	String[] cities = 
		{
				"Manhattan","Brooklyn","Bronx","Queens","Newyorkcity","NewYork","NewJersey","Staten Island","New York City",
				"New York", "New Jersey","NJ","NY","NYC","Hudson River",
				"Yonkers","MiddleTown","Edison",
				"Hamilton Township","Bay Head",
				"New Rochelle ",
				"Hempstead"
		};
}
